### ISSUE TITLE
ModInfo.xml details

### ISSUE THREAD

**Issue by XelaNull** [n4bb12/7d2d-balance#1]
Hello -- I'm working on a 7DTD dedicated server mod manager for Linux. Currently it has around 60 packages with nearly 500 modlets included. The web interface for it reads in the ModInfo.xml in order to determine what each mod does. Most people include just a sentence or two in order to briefly explain what the modlet. Your modlets are the only I've found that all say "See a full list of changes in the README" instead of actually explaining what the modlet does. I'm hoping some day my mod manager will be used by a lot of people who would really benefit by your modlets having this detail filled in.
![screen shot 2019-03-03 at 21 24 05](https://user-images.githubusercontent.com/46318155/53706945-bb991180-3dfa-11e9-989a-6b6941da1506.png)

https://github.com/XelaNull/7dtd-servermod

**Comment by n4bb12** [comment]
Thanks for the hint, I added the descriptions to the `ModInfo.xml`.
https://github.com/n4bb12/7d2d-balance/blob/master/dist/n4bb12_AutoDestroyBirdsNest/ModInfo.xml
